name: Airflow k8s DAGs Test

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: run docker webserver
      run: |
        pwd
        ls -la
        docker run -p 8080:8080 \
        -v dags/:/usr/local/airflow/dags \
        -v plugins/:/usr/local/airflow/plugins \
        puckel/docker-airflow webserver
