name: Airflow k8s DAGs Test

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: run docker webserver
      run: |
        docker run -p 8080:8080 -e LOAD_EX=./dags puckel/docker-airflow webserver
