name: Airflow k8s DAGs Test

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: run docker webserver
      run: |
        curl -LfO 'https://airflow.apache.org/docs/apache-airflow/1.10.14/docker-compose.yaml'
        mkdir ./dags ./logs ./plugins
        echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
        docker-compose up airflow-init
        docker-compose up
