name: Airflow k8s DAGs Test

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: run docker webserver
      run: |
        docker run -it \
           -e "AIRFLOW__CORE__PLUGINS_FOLDER='/opt/plugins' \
           -e "AIRFLOW__CORE__DAGS_FOLDER='/opt/dags' \
           -e "AIRFLOW_DB_UPGRADE=true" \
           --mount type=bind,source=dags,target=/opt/dags \
           --mount type=bind,source=plugins,target=/opt/plugins \
           apache/airflow:master-python3.6 airflow webserver